# Generated by Django 4.0.5 on 2022-09-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_alter_user_room"),
        ("Memos", "0002_memo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.user",
            ),
        ),
    ]
