# Generated by Django 4.0.5 on 2022-09-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_user_room_admin"),
        ("Memos", "0003_alter_memo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Users.user"
            ),
        ),
    ]
