# Generated by Django 4.0.5 on 2022-10-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('nickname', models.CharField(default='', max_length=45)),
                ('email', models.CharField(default='', max_length=90)),
                ('available', models.CharField(default='', max_length=45)),
                ('expenses_amt', models.FloatField(default=0)),
                ('room_admin', models.BooleanField(default=0)),
                ('chore_weight', models.IntegerField(default=1)),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Rooms.room')),
            ],
        ),
    ]
