# Generated by Django 4.0.5 on 2022-09-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="room_id",
            new_name="room",
        ),
    ]
