# Generated by Django 4.0.5 on 2022-09-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0003_alter_room_admin"),
        ("Users", "0002_rename_room_id_user_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="room",
            field=models.ForeignKey(
                default=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Rooms.room",
            ),
        ),
    ]
