# Generated by Django 4.0.5 on 2022-09-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_alter_user_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="room_admin",
            field=models.BooleanField(default=0),
        ),
    ]
