# Generated by Django 4.0.5 on 2022-09-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0004_remove_room_admin"),
        ("Users", "0004_user_room_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="room",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="Rooms.room",
            ),
        ),
    ]
