# Generated by Django 4.0.5 on 2022-08-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('num_members', models.IntegerField(default=0)),
                ('chore_cycle_len', models.IntegerField(default=0)),
                ('set_up', models.BooleanField(default=0)),
            ],
        ),
    ]
