# Generated by Django 4.0.5 on 2022-09-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_rename_room_id_user_room"),
        ("Rooms", "0002_room_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="Users.user",
            ),
        ),
    ]
