# Generated by Django 4.0.5 on 2022-09-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0003_alter_room_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="admin",
        ),
    ]
