# Generated by Django 4.0.5 on 2022-08-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Expenses", "0003_expense_room_id_alter_expense_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="room_id",
            new_name="room",
        ),
    ]
