# Generated by Django 4.0.5 on 2022-08-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=45)),
                ("completed", models.BooleanField(default=0)),
                ("weight", models.IntegerField(default=0)),
            ],
        ),
    ]
