# Generated by Django 4.0.5 on 2022-08-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chores', '0002_chore_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='room_id',
            new_name='room',
        ),
    ]
