# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoomHub' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  # Pods for RoomHub

  target 'RoomHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoomHubUITests' do
    # Pods for testing
  end

end
